In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [4]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['Species']=iris.target

print("Dataset Preview :")
print(df.head())

Dataset Preview :
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Species  
0        0  
1        0  
2        0  
3        0  
4        0  


In [6]:
X=iris.data
y=iris.target
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

print("\n Training Data Size :",X_train.shape)
print("\n Testing Data Size :",X_test.shape)
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
print("\n Predicted Values :")
print(y_pred)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy Score",accuracy)

print("\n Confusion Matrix :")
print(confusion_matrix(y_test,y_pred))

print("\n Classification Report :")
print(classification_report(y_test,y_pred))

new_sample=[[5.1,3.5,1.4,0.2]]


 Training Data Size : (120, 4)

 Testing Data Size : (30, 4)

 Predicted Values :
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Accuracy Score 1.0

 Confusion Matrix :
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

 Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [7]:
new_sample=[[5.1,3.5,1.4,0.2]]
prediction=knn.predict(new_sample)
print("\n Prediction For New Sample :",prediction)
print("Predicted Flower Type :",iris.target_names[prediction][0])


 Prediction For New Sample : [0]
Predicted Flower Type : setosa


In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
wine=load_wine()
df=pd.DataFrame(wine.data,columns=wine.feature_names)

df['wine_class']=wine.target

print("Dataset preview :")
print(df.head())
print("\n Alcohol Feature Values :")
print(df['alcohol'])
X=wine.data
y=wine.target

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42)

print("\n Training Data Size :",X_train.shape)
print("\n Testing Data size : ",X_test.shape)

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

y_pred=knn.predict(X_test)
print("\n Predicted Values :")
print(y_pred)
accuracy=accuracy_score(y_test,y_pred)
print("Model Accuracy :",accuracy)


print("Confusion_Matrix",confusion_matrix(y_test,y_pred))
new_sample=[[13.2,2.7,2.4,18.5,100,2.5,2.1,0.3,1.7,5.0,1.0,3.2,900]]
prediction=knn.predict(new_sample)
print("predicted wine Class :",prediction[0])
print("Predicted Wine type :",wine.target_names[prediction][0])

Dataset preview :
   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  wi