In [1]:
import numpy as np
arr1=np.arange(2,21,2) # print 2 to 20 only even numbers
print(arr1)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
arr2=np.linspace(0,1,5) #Array of 5 Equally spaced Number between 0 to 1
print(arr2)

[0.   0.25 0.5  0.75 1.  ]


In [4]:
arr3=np.full((3,3),7) #3x3 array Filled With 7
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [6]:
arr4=np.eye(4)  #4x4 Identity Matrix
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
arr5=np.random.rand(10) #array of 10 random floating-point numbers between 0 and 1
print(arr5)

[0.24190735 0.79961675 0.33407924 0.02488817 0.60428033 0.18942591
 0.75679784 0.33882567 0.97403917 0.77925988]


In [9]:
arr6=np.arange(1,13).reshape(3,4) #reshape 1D Array number from 1 to 12 into a 3x4 Matrix
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(arr6.reshape) #Shape of Array
print(arr6.ndim) #shape of Dimension

<built-in method reshape of numpy.ndarray object at 0x000001F4233E4210>
2


In [12]:
arr8=np.arange(1,26).reshape(5,5)  #array 1 to 25 reshape it into 5x5 matrix
print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
first_row=arr8[0] #Extract First Row in Array
print(first_row)

[1 2 3 4 5]


In [16]:
last_column=arr8[:,-1] #Extract last Column form array
print(last_column)

[ 5 10 15 20 25]


In [17]:
arr8[arr8>15]=0 #replace all value greater than 15 in the array with 0
print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
