In [1]:
import numpy as nm

In [2]:
arr=nm.array([12,85,54,14,41])
print(arr)

[12 85 54 14 41]


In [4]:
b=nm.array([[5,12,54],[41,256,52],[54,12,41]]) #MultiDimension Array
print(b)

[[  5  12  54]
 [ 41 256  52]
 [ 54  12  41]]


In [5]:
print("Dimension :",arr.ndim) #ndim used to display Dimension of An Array

Dimension : 1


In [6]:
print(b.ndim)

2


In [7]:
print("Shape :",b.shape) #Display Size OF Array

Shape : (3, 3)


In [10]:
print("Type :",b.dtype) #DataType

Type : int64


In [12]:
x=nm.array([41,59,85])
y=nm.array([10,54,26])

print("X + Y",x+y)
print("X - Y",x-y)
print("X * Y",x*y)
print("X / Y",x/y)

X + Y [ 51 113 111]
X - Y [31  5 59]
X * Y [ 410 3186 2210]
X / Y [4.1        1.09259259 3.26923077]


In [16]:
add=nm.add(x,y)
print("Subtraction",nm.subtract(x,y))
print("Multiplication",nm.multiply(x,y))
print("Division",nm.divide(x,y))
print("Modulo",nm.mod(x,y))

Subtraction [31  5 59]
Multiplication [ 410 3186 2210]
Division [4.1        1.09259259 3.26923077]
Modulo [1 5 7]


In [18]:
a=nm.array([10,20,30,
           40,50,52,36,441])

print("Max Value :",nm.max(a))
print("Min Value :",nm.min(a))
print("Sum Value :",nm.sum(a))
print("Mean Value :",nm.mean(a))#average

Max Value : 441
Min Value : 10
Sum Value : 679
Mean Value : 84.875


In [20]:
array1=nm.array([[96,74,63],[85,74,96]])
array2=nm.array([[25,55,41],[96,15,45]])
print("Addition",nm.add(array1,array2))
print("Subtraction",nm.subtract(array1,array2))
print("Modulas",nm.mod(array1,array2))
print("Mean",nm.mean(array1))
print("Mean",nm.mean(array2))
print("Sum",nm.sum(array1))
print("Sum",nm.sum(array2))


Addition [[121 129 104]
 [181  89 141]]
Subtraction [[ 71  19  22]
 [-11  59  51]]
Modulas [[21 19 22]
 [85 14  6]]
Mean 81.33333333333333
Mean 46.166666666666664
Sum 488
Sum 277
