In [2]:
import numpy as np

In [4]:
arr1=np.arange(2,21,2)
print(arr1)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
arr2=np.linspace(0,1,5)
print(arr2)

[0.   0.25 0.5  0.75 1.  ]


In [9]:
arr3=np.full((3,3),7)
print(arr3)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [11]:
arr4=np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
arr5=np.random.rand(10)
print(arr5)

[0.41430634 0.1141453  0.29110308 0.13587154 0.44755965 0.68968873
 0.87612509 0.55871396 0.94725391 0.71486949]


In [15]:
arr6=np.arange(1,13).reshape(3,4)
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr6.reshape)
print(arr6.ndim)


<built-in method reshape of numpy.ndarray object at 0x000001DAEC56DE30>
2


In [19]:
arr8=np.arange(1,26).reshape(5,5)
print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [21]:
first_row=arr8[0]
print(first_row)

[1 2 3 4 5]


In [22]:
last_column=arr8[:,-1]
print(last_column)

[ 5 10 15 20 25]


In [23]:
arr8[arr8>15]=0
print(arr8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
