In [4]:
import numpy as nm

In [5]:
arr=nm.array([12,85,54,14,41])
print(arr)

[12 85 54 14 41]


In [8]:
b=nm.array([[5,12,54],[41,256,52],[54,12,41]])
print(b)

[[  5  12  54]
 [ 41 256  52]
 [ 54  12  41]]


In [9]:
print("Diamension :",arr.ndim)

Diamension : 1


In [10]:
print("Shape :",b.shape)

Shape : (3, 3)


In [12]:
print("Type :",b.dtype)

Type : int64


In [13]:
x=nm.array([41,59,85])
y=nm.array([10,54,26])

print("X+Y",x+y)
print("X-Y",x-y)
print("X*Y",x*y)
print("X/Y",x/y)


X+Y [ 51 113 111]
X-Y [31  5 59]
X*Y [ 410 3186 2210]
X/Y [4.1        1.09259259 3.26923077]


In [14]:
add=nm.add(x,y)
print("Subtraction :",nm.subtract(x,y))
print("Multiplication :",nm.multiply(x,y))
print("Division :",nm.divide(x,y))
print("modulo :",nm.mod(x,y))

Subtraction : [31  5 59]
Multiplication : [ 410 3186 2210]
Division : [4.1        1.09259259 3.26923077]
modulo : [1 5 7]


In [15]:
a=nm.array([10,20,30,40,50,52,36,441])
print("Max Value :",nm.max(a))
print("Min Value :",nm.min(a))
print("Sum Value :",nm.sum(a))
print("Mean Value :",nm.mean(a))


Max Value : 441
Min Value : 10
Sum Value : 679
Mean Value : 84.875


In [18]:
array1=nm.array([[96,74,69],[85,74,56]])
array2=nm.array([[74,55,75],[14,56,98]])
print("Addition :",nm.add(array1,array2))
print("Subtraction :",nm.subtract(array1,array2))
print("Modulas :",nm.mod(array1,array2))
print("Mean :",nm.mean(array1))
print("Mean :",nm.mean(array2))
print("Sum :",nm.sum(array1))
print("Sum :",nm.sum(array2))


Addition : [[170 129 144]
 [ 99 130 154]]
Subtraction : [[ 22  19  -6]
 [ 71  18 -42]]
Modulas : [[22 19 69]
 [ 1 18 56]]
Mean : 75.66666666666667
Mean : 62.0
Sum : 454
Sum : 372
