In [2]:
import numpy as np

In [5]:
array=np.array([[15,52],[74,69]])
print(np.sqrt(array))

[[3.87298335 7.21110255]
 [8.60232527 8.30662386]]


In [6]:
print(array.T)

[[15 74]
 [52 69]]


In [7]:
b1=np.array([[5,7],[4,9]])
b2=np.array([[1,2],[5,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi)

[[40 66]
 [49 80]]


In [8]:
c1=np.zeros([3,3])
print(c1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
c1=np.ones([3,3])
print(c1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
bool=np.array([[True,True],[True,False]])
print("All() with Axis 0 :",np.all(bool))
print("All() with Axis None :",np.all(bool,axis=0))


All() with Axis 0 : False
All() with Axis None : [ True False]


In [13]:
a1=np.arange(1,10,2)
print(a1)

[1 3 5 7 9]


In [14]:
a2=np.arange(9)
print(a2)
reshape=a2.reshape(3,3)
print(reshape)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
re=reshape[:,:2]
print(re)

[[0 1]
 [3 4]
 [6 7]]


In [16]:
x=np.array([[45,85],[65,85]])
y=np.array([[42,87],[69,85]])
z=np.array([[65,42],[74,45]])
print(x)
print(y)
print(z)


[[45 85]
 [65 85]]
[[42 87]
 [69 85]]
[[65 42]
 [74 45]]


In [17]:
print("Horizontal Stack")
h=np.hstack((x,y,z))
print(h)

Horizontal Stack
[[45 85 42 87 65 42]
 [65 85 69 85 74 45]]


In [20]:
print("Vertical Stack")
v=np.vstack((x,y,z))
print(v)

Vertical Stack
[[45 85]
 [65 85]
 [42 87]
 [69 85]
 [65 42]
 [74 45]]


In [21]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
print("Horizontal Split Stack")
h=np.split(arr,2)
print(h)

Horizontal Split Stack
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [24]:
print("Vertical Split Stack")
v=np.vsplit(arr,2)
print(v)

Vertical Split Stack
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [26]:
pv=np.array([85,74,69,25])
print("Sqrt :",np.sqrt(pv))
print("Exp :",np.exp(pv))
print("Sin :",np.sin(pv))
print("Cos :",np.cos(pv))
print("Std :",np.std(pv))


Sqrt : [9.21954446 8.60232527 8.30662386 5.        ]
Exp : [8.22301271e+36 1.37338298e+32 9.25378173e+29 7.20048993e+10]
Sin : [-0.17607562 -0.98514626 -0.11478481 -0.13235175]
Cos : [-0.98437664  0.17171734  0.99339038  0.99120281]
Std : 22.829531313629722


In [28]:
print("Random :",format(np.random.random(20)))

Random : [0.05596107 0.21818494 0.8602391  0.42152703 0.16053776 0.1111368
 0.57245551 0.00108779 0.67630274 0.34710683 0.24604552 0.83812478
 0.43852149 0.51769638 0.84924455 0.66737568 0.00132749 0.39344669
 0.33961897 0.78652602]


In [31]:
print("2D Array Random :",format(np.random.rand(3,4)))

2D Array Random : [[0.6572717  0.22905924 0.94107981 0.56930515]
 [0.18109662 0.37350282 0.16378501 0.9803479 ]
 [0.24734656 0.04649306 0.2572767  0.16067746]]


In [33]:
print("Random Integration :",format(np.random.randint(0,100,20)))

Random Integration : [56 25 92 87 79 14 94 23 35 76 65 17 82  9 90 33 58 86 75 32]


In [38]:
print("Permutation :",format(np.random.permutation(np.arange(20))))

Permutation : [19 12  6 13  1 16 14  5  4 18 10  9  7  8  3 17  2 15  0 11]
