In [2]:
import numpy as np

In [3]:
arr=np.array(list(range(5)))
print(arr)

[0 1 2 3 4]


In [6]:
arr=np.arange(10,100,10)
print(arr)

[10 20 30 40 50 60 70 80 90]


In [8]:
import string
arr=np.array(list(string.ascii_uppercase))
print(arr)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [9]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
print(arr.dtype)

float64


In [14]:
arr=np.random.randint(1,6,size=10)
print(arr)

[5 4 3 5 2 5 5 5 2 5]


In [15]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
odd=arr[arr%2==1]
print(odd)

[1 3 5 7 9]


In [19]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[arr%2==1]=-1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1]
